---
title: 异步与同步
---

## 异步

### Promise

```js
new Promise(function (resolve, reject) {
  var a = 0;
  var b = 1;
  if (b == 0) reject("Diveide zero");
  else resolve(a / b);
})
  .then(function (value) {
    console.log("a / b = " + value);
    return value + 1;
  })
  .then(function (value) {
    console.log(value);
  })
  .catch(function (err) {
    console.log(err);
  })
  .finally(function () {
    console.log("End");
  });
```

- 调用 `resolve` 代表一切正常，`reject` 是出现异常时所调用的。
  - `resolve` 传入的参数在第一个 `then` 调用。
  - `reject` 传入的参数在 `catch` 调用。
  - `then` 返回的值在下一个 `then` 调用。
- `resolve` 和 `reject` 的作用域只有起始函数，不包括 `then` 以及其他序列。
- `resolve` 和 `reject` 并不能够使起始函数停止运行，请用 `return`。

```js
function print(delay, message) {
  return new Promise(function (resolve, reject) {
    setTimeout(function () {
      console.log(message);
      resolve();
    }, delay);
  });
}

print(1000, "First")
  .then(function () {
    return print(4000, "Second");
  })
  .then(function () {
    print(3000, "Third");
  });
```

#### 生命周期

`Promise` 对象有以下几种状态：

- pending：初始的状态，即正在执行，不处于 fulfilled 或 rejected 状态。
- fulfilled：成功的完成了操作。
- rejected：失败，没有完成操作。
- settled：Promise 处于 fulfilled 或 rejected 二者中的任意一个状态, 不会是 pending。

![Promise 生命周期](https://mdn.mozillademos.org/files/8633/promises.png)

### Async

异步函数 `async function` 中可以使用 `await` 指令，`await` 指令后必须跟着一个 `Promise`，异步函数会在这个 `Promise` 运行中暂停，直到其运行结束再继续运行。

```js
async function asyncFunc() {
  await print(1000, "First");
  await print(4000, "Second");
  await print(3000, "Third");
}
asyncFunc();
```

处理异常的机制将用 try-catch 块实现

```js
async function asyncFunc() {
  try {
    await new Promise(function (resolve, reject) {
      throw "Some error"; // 或者 reject("Some error")
    });
  } catch (err) {
    console.log(err);
    // 会输出 Some error
  }
}
asyncFunc();
```
